# Github workflow runner for Docker Multi-Arch using QEMU, Buildx for amd64 & arm64
#
### Note - I got this interesting file from:
### https://blog.devgenius.io/how-to-build-your-docker-images-using-multi-arch-to-support-arm64-m1-macbook-6ebc42a47cd7
name: Docker Multi-Arch

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: build for amd64/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
        # Setup hardware emulator using QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
        # Setup Docker Buildx for multi-arch images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.__YOUR__PERSONAL__GITHUB__TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
